//
// Created by 24SFAERBER on 3/21/2023.
//

#ifndef ASCIIADVENTUREGAME_SAVEFILEMANAGER_H
#define ASCIIADVENTUREGAME_SAVEFILEMANAGER_H


class SaveFileManager {

};


#endif //ASCIIADVENTUREGAME_SAVEFILEMANAGER_H
